spring:
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

token:
  secret:
    key : linkeepServerJwtTokenSecretKey!!
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12
